cordova plugin add custom_plugin/cordova-plugin-camera
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-dialogs
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-file
cordova plugin add cordova-plugin-network-information
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-file-transfer
cordova plugin add cordova-plugin-android-imei
cordova plugin add cordova-plugin-advanced-geolocation
cordova plugin add cordova-plugin-locationservices
cordova plugin add org.apache.cordova.geolocation
cordova plugin add cordova.plugins.diagnostic
cordova plugin add com.adjust.sdk
cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
cordova plugin add phonegap-plugin-barcodescanner
cordova plugin add cordova-plugin-request-location-accuracy
